# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a72bd88e876c980b110e82be96efeefab6dcd3033c0c4af1e212d87c4b37580eab94805870d3b30b238dead682dac5a53cd99679c396b75a73a48debb9fa4837

test:
  secret_key_base: be3b0096fd1ef749f8531ddb2a634ae310f653cbc57ac46f54d2f178bfb997bf46c98499b0963e38d37dd3f94f71966855be5eb1f11da07e5ecfc8cc599aa24d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
